/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_MyNativeMethodExample */

#ifndef _Included_jni_MyNativeMethodExample
#define _Included_jni_MyNativeMethodExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_MyNativeMethodExample
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_MyNativeMethodExample_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
